=== lucaseguii/XML-Luca-Segui/UD3. Exercicis pack 6 LUCA SEGUI/expedients.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="expedients">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="expedient" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="titulacio" type="xs:string"/>
              <xs:element name="estudiant" type="xs:string"/>
              <xs:element name="moduls">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="modul" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:attribute name="nom" type="xs:string" use="required"/>
                        <xs:attribute name="aprovat" type="xs:boolean" use="required"/>
                        <xs:attribute name="curs" use="required">
                          <xs:simpleType>
                            <xs:restriction base="xs:string">
                              <xs:enumeration value="Primer"/>
                              <xs:enumeration value="Segon"/>
                            </xs:restriction>
                          </xs:simpleType>
                        </xs:attribute>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== lucaseguii/XML-Luca-Segui/UD3. Exercicis pack 6 LUCA SEGUI/activitat6_2.xml
<?xml version="1.0" encoding="UTF-8"?>
<expedients
xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
xs:noNamespaceSchemaLocation="expedients.xsd">
<expedient>
<titulacio>DAM</titulacio>
<estudiant>Ainhoa Gárate Lizarraga</estudiant>
<moduls>
<modul nom="Sistemes informàtics" aprovat="true"
curs="Primer"/>
<modul nom="Llenguatge de marques i sistemes de gestió de la
informació" aprovat="true" curs="Primer"/>
<modul nom="Programació multimèdia i dispositius mòvils"
aprovat="false" curs="Segon"/>
</moduls>
</expedient>
<expedient>
<titulacio>DAW</titulacio>
<estudiant>Ferran Soler Puig</estudiant>
<moduls>
<modul nom="Programació" aprovat="true" curs="Primer"/>
<modul nom="Desenvolupament web en entorn client"
aprovat="false" curs="Segon"/>
<modul nom="Desenvolupament web en entorn servidor"
aprovat="false" curs="Segon"/>
</moduls>
</expedient>
</expedients>
