=== lucaseguii/XML-Luca-Segui/UD3. Exercicis pack 6 LUCA SEGUI/subhasta.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="subhasta">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="objecte" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="propietari" type="xs:string"/>
              <xs:element name="preu_sortida">
                <xs:simpleType>
                  <xs:restriction base="xs:decimal">
                    <xs:totalDigits value="6"/>
                    <xs:fractionDigits value="2"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="preu_minim" type="xs:decimal" minOccurs="0"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== lucaseguii/XML-Luca-Segui/UD3. Exercicis pack 6 LUCA SEGUI/activitat6_3.xml
<?xml version="1.0" encoding="UTF-8"?>
<subhasta xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
  xs:noNamespaceSchemaLocation="subhasta.xsd">
  <objecte>
    <propietari>Dani Segura</propietari>
    <preu_sortida>1200.50</preu_sortida>
    <preu_minim>1000.00</preu_minim>
  </objecte>
  <objecte>
    <propietari>Adri Garcia</propietari>
    <preu_sortida>800.75</preu_sortida>
  </objecte>
</subhasta>
