=== lucaseguii/XML-Luca-Segui/UD3. Exercicis pack 6 LUCA SEGUI/temperatura.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="registre_temperatura">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="provincia" type="xs:string"/>
        <xs:element name="data" type="xs:date"/>
        <xs:element name="temperatura_minima">
          <xs:simpleType>
            <xs:restriction base="xs:integer">
              <xs:minInclusive value="-50"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element name="temperatura_maxima">
          <xs:simpleType>
            <xs:restriction base="xs:integer">
              <xs:maxInclusive value="50"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element name="incidencies">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="incidencia" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:attribute name="nom" use="required">
                    <xs:simpleType>
                      <xs:restriction base="xs:string">
                        <xs:enumeration value="fred"/>
                        <xs:enumeration value="neu"/>
                        <xs:enumeration value="pluja"/>
                        <xs:enumeration value="calor"/>
                      </xs:restriction>
                    </xs:simpleType>
                  </xs:attribute>
                  <xs:attribute name="severitat" use="required">
                    <xs:simpleType>
                      <xs:restriction base="xs:string">
                        <xs:enumeration value="alta"/>
                        <xs:enumeration value="mitja"/>
                        <xs:enumeration value="baixa"/>
                      </xs:restriction>
                    </xs:simpleType>
                  </xs:attribute>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== lucaseguii/XML-Luca-Segui/UD3. Exercicis pack 6 LUCA SEGUI/activitat6_1.xml
<?xml version="1.0" encoding="UTF-8"?>
<registre_temperatura
xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
xs:noNamespaceSchemaLocation="temperatura.xsd">
<provincia>Zamora</provincia>
<data>2022-01-07</data>
<temperatura_minima>-5</temperatura_minima>
<temperatura_maxima>4</temperatura_maxima>
<incidencies>
<incidencia nom="fred" severitat="alta"/>
<incidencia nom="neu" severitat="alta"/>
<incidencia nom="pluja" severitat="mitja"/>
</incidencies>
</registre_temperatura>
